
### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "user4@test.com", 
    "password" : "user4"
} 

###Get the signedin user
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "user4@test.com", 
    "password" : "user4"
} 
 

### Check the existing user
GET http://localhost:3000/auth/whoami



### Signout user
POST http://localhost:3000/auth/signout


###Find a particular user with a given ID:
GET http://localhost:3000/auth/3

###Find a particular user based on email:

GET http://localhost:3000/auth?email=ejbaho@yahoo.com


 
###Remove a user/with a particular id : 
DELETE http://localhost:3000/auth/12122 

### Update a user
PATCH  http://localhost:3000/auth/123123234 

content-type: application/json

{
    "password" : "asfsfsdfsdf"
}
 

### Set a color
Get http://localhost:3000/auth/colors/blue 


### Get a color
Get http://localhost:3000/auth/colors 


# testing