
### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "test1@test.com", 
    "password" : "12345"
} 

### Sign in as an existing user
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "test@test.com", 
    "password" : "12345"
} 


###Find a particular user with a given ID:
GET http://localhost:3000/auth/3

###Find a particular user based on email:

GET http://localhost:3000/auth?email=ejbaho@yahoo.com



###Remove a user/with a particular id : 
DELETE http://localhost:3000/auth/12122 

### Update a user
PATCH  http://localhost:3000/auth/123123234 

content-type: application/json

{
    "password" : "asfsfsdfsdf"
}
 

### Set a color
Get http://localhost:3000/auth/colors/blue 


### Get a color
Get http://localhost:3000/auth/colors 
